export const LONG_TEST_FILES = [
  'src/simulation/FullStandardRaceTyrePlaytest.test.ts',
  'src/simulation/CompactStrategyPhysicsPlaytest.test.ts',
  'src/simulation/EditorCircuitPlaytest.test.ts',
  'src/simulation/AiReferenceGhost.test.ts',
  'src/simulation/DynamicPackPlaytest.test.ts',
  'src/simulation/MultiCircuitPlaytest.test.ts',
  'src/simulation/PlayerLinePlaytest.test.ts',
  'src/simulation/ProDriverRegression.test.ts',
  'src/simulation/ReferenceDriverModel.test.ts',
] as const;

export const PLAYTEST_TEST_FILES = [
  'src/simulation/RacePerformance.test.ts',
  'src/game/GrandPrixPlaytest.test.ts',
  'src/game/PitEconomicsPlaytest.test.ts',
  'src/game/PlayerPitCapturePlaytest.test.ts',
  'src/rendering3d/PitLane3D.test.ts',
  'src/simulation/AeroFeedbackRegression.test.ts',
  'src/simulation/AiStuckRecoveryPhysics.test.ts',
  'src/simulation/CarImpactPhysics.test.ts',
  'src/simulation/AiTrafficLineRegression.test.ts',
  'src/simulation/AiPhysicalPit.test.ts',
  'src/simulation/PitTrafficStrategyPlaytest.test.ts',
  'src/simulation/DynamicAiController.test.ts',
  'src/simulation/GridLaunchRegression.test.ts',
  'src/simulation/LapValidityModel.test.ts',
  'src/simulation/QualifyingModel.test.ts',
  'src/simulation/RaceStartRegression.test.ts',
  'src/simulation/RacingLineRuntime.test.ts',
  'src/simulation/SharedChassisRegression.test.ts',
  'src/simulation/TrackBarrierPhysics.test.ts',
  'src/simulation/TrackModel.test.ts',
  'src/simulation/TyreStrategyPlaytest.test.ts',
] as const;
